name: ci_build

env:
  DEBIAN_FRONTEND: noninteractive

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_build.yml"

jobs:

  linux_no_mpi:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build
    - run: cmake --build build --parallel

    - name: unit tests
      run: ctest -R unit --parallel 4 --output-on-failure
      working-directory: build

    - name: 2D test without MPI
      run: ctest -R 2dew_fang --parallel 4 --output-on-failure
      working-directory: build


  linux_mpi:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2

    # have to have openmpi-bin as unlike full install it's not auto-installed here
    # libhdf5-dev just to speed up CI
    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin libhdf5-dev

    - run: cmake -B build
    - run: cmake --build build --parallel

    - run: ctest -R unit
      working-directory: build

    - run: ctest -E 3d --parallel 4 --output-on-failure
      working-directory: build


  mac_no_mpi:
    if: false  # save CI time, works fine
    needs: linux_no_mpi
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install gcc ninja lapack hdf5
      timeout-minutes: 5
      # transient CI download speed

    - run: cmake -B build
      timeout-minutes: 5

    - run: cmake --build build --parallel
      timeout-minutes: 5

    - name: Unit tests
      run: ctest -R unit --parallel 4 --output-on-failure
      working-directory: build
      timeout-minutes: 2

    - name: 2D test without MPI
      run: ctest -R 2dew_fang --parallel 4 --output-on-failure
      working-directory: build
      timeout-minutes: 5
