name: ci_debug_build
env:
  CI: true

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - ".github/workflows/ci_debug_build.yml"
  pull_request:
    paths:
      - "**.f90"
      - "**.F90"
      - ".github/workflows/ci_debug_build.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: |
        pip install -e .
        pip install cmake
    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran liblapack-dev libscalapack-openmpi-dev libmumps-dev libopenmpi-dev openmpi-bin libhdf5-dev octave

    - run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -Dhdf5=true
      env:
        FC: gfortran
    - run: cmake --build build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_CMake_DebugBuildlog
        path: build/CMakeFiles/CMakeError.log

    - run: ctest --parallel --output-on-failure -R unit
      working-directory: build
    - run: ctest --parallel --output-on-failure -R 2d_fang
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_CMake_DebugTestlog
        path: build/Testing/Temporary/LastTest.log
