name: ci_linux

env:
  DEBIAN_FRONTEND: noninteractive
  CTEST_PARALLEL_LEVEL: 2

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_linux.yml"

jobs:

  cmake-hdf5:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo cmake -P scripts/install_prereq.cmake

# CI is too slow for 3d_glow
    - run: cmake --preset default
    - run: cmake --build build --parallel

    - run: ctest --preset default -E 3d


  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
    - uses: actions/checkout@v2

    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo cmake -P scripts/install_prereq.cmake

    - run: cmake --preset default -DCMAKE_BUILD_TYPE=Debug
    - run: cmake --build build --parallel

    - run: ctest --preset default -R "(unit|2dew_fang)"
