name: ci_linux
env:
  CI: true

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_linux.yml"
  pull_request:
  release:


jobs:

  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: |
        pip install -e .
        pip install cmake
    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends pkg-config gfortran libopenmpi-dev openmpi-bin liblapack-dev libscalapack-openmpi-dev libmumps-dev libhdf5-dev octave
    - name: Install Ninja
      run: |
        wget https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
        unzip ninja-linux.zip

    - name: CMake configure
      run: cmake -G Ninja -DCMAKE_MAKE_PROGRAM=$(realpath ./ninja) -B build -Dhdf5=true
      env:
        FC: gfortran
    - run: cmake --build build --parallel
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Cmake_Buildlog
        path: build/CMakeFiles/CMakeError.log
# CI is too slow for 3d_glow

# -V output truncated on CI?
    - run: ctest --parallel --output-on-failure -R unit
      working-directory: build
    - run: ctest --parallel --output-on-failure -R 2d
      working-directory: build
    - run: ctest --parallel --output-on-failure -R 3d_fang
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_CMake_Testlog
        path: build/Testing/Temporary/LastTest.log


  cmakeBuildAllLibs:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: |
        pip install -e .
        pip install cmake
    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends pkg-config gfortran libopenmpi-dev openmpi-bin


    - name: CMake configure
      run: cmake -B build -Dhdf5=true
      env:
        FC: gfortran
    - run: cmake --build build --parallel
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: LinuxOS_Cmake_Buildlog
        path: build/CMakeFiles/CMakeError.log

# -V output truncated on CI?
    - run: ctest --parallel --output-on-failure -R unit
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_CMake_Testlog
        path: build/Testing/Temporary/LastTest.log
