name: ci_macos
env:
  CI: true

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_macos.yml"
  pull_request:


jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install -e .
    - run: brew install pkg-config ninja lapack open-mpi hdf5 scalapack

# CI is too slow for 3d_glow
    - run: ctest -S cdash.cmake -E 3d -VV
      env:
        FC: gfortran-9
        CC: gcc-9
