name: ci_python

on:
  push:
    paths:
    - "**/*.py"
    - ".github/workflows/ci_python.yml"
  pull_request:
    paths:
    - "**/*.py"
    - ".github/workflows/ci_python.yml"
  release:


jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - run: python3 -m pip install -e .[lint]
    - run: flake8
    - run: mypy .
