name: ci_rawio
# for non-HDF5 I/O

env:
  CI: true

on:
  push:
    paths:
    - "**/*.cmake"
    - ".github/workflows/ci_rawio.yml"
  pull_request:
  release:

jobs:

  cmake:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python3 -m pip install -e .[tests]
    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin liblapack-dev libscalapack-mpi-dev libmumps-dev libpthread-stubs0-dev octave
        pip install cmake

    - name: CMake configure
      run: cmake -B build -Dhdf5=false
      env:
        FC: gfortran
    - run: cmake --build build --parallel
# CI is too slow for 3d_glow
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: LinuxRawIO_Cmake_Buildlog
        path: build/CMakeFiles/CMakeError.log

# -V output truncated on CI?
    - run: ctest --output-on-failure -R 2d
      working-directory: build
    - run: ctest --output-on-failure -R 3d_fang
      working-directory: build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: LinuxRawIO_CMake_Testlog
        path: build/Testing/Temporary/LastTest.log
