name: ci_windows

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLEL_LEVEL: 2

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"
# paths ignore starting with "!"
      - "!docs/**"
      - "!scripts/**"

jobs:

  windows_no_mpi:
    # it's tricky to install mpiexec automatically on Windows (see p4est)
    # thus it's convenient to use Windows as a no-MPI, no-hwloc test case
    timeout-minutes: 20
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          patch
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-hdf5
          mingw-w64-x86_64-lapack

    - uses: actions/checkout@v2

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v2
      with:
        repository: gemini3d/external
        path: gemext

    - name: Put MSYS2_MinGW64 on PATH
      # this is because GNU Patch doesn't work from MSYS2 shell
      run: echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install numeric libraries
      timeout-minutes: 8
      run: |
        cmake -S gemext -B gemext/build -Dfind:BOOL=true -Dusempi:BOOL=no "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/.."
        cmake --build gemext/build --target ffilesystem glow msis mumps mpi_scalapack_stub
        cmake --install gemext/build

    - name: Configure multi
      run: cmake -Dmpi=no --preset multi "-DCMAKE_PREFIX_PATH:PATH=${{ github.workspace }}/.."


    - name: Debug build
      run: cmake --build --preset debug

    - name: Debug unit test
      run: ctest --preset debug -L unit

    - name: Debug core test
      run: ctest --preset debug -LE unit -R "(2dew_fang|2dns_fang)"


    - name: Release build
      run: cmake --build --preset release

    - name: Release unit test
      run: ctest --preset release -L unit

    - name: Release core test
      run: ctest --preset release -LE unit -E 3d
